server:
  port: 9090
  address: 13.48.29.69

spring:
  application:
    name: msvc-InventoryReportsAPI

  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/reportsdb
    url: jdbc:postgresql://reportsdb.cv4qesycas0y.eu-north-1.rds.amazonaws.com:5432/reportsdb
    username: postgres
    #password: curso
    password: D1p4w38Cu*
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://13.48.29.69:8761/eureka