server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: msvc-ApiGateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: InventoryManagementCRUDAPI
          uri: http://127.0.0.1:8090
          predicates:
            - Path=/api/crud/**
        - id: InventoryReportsAPI
          uri: http://127.0.0.1:9090
          predicates:
            - Path=/api/inform/**
