server:
  port: 8090
  address: 13.48.29.69

spring:
  application:
    name: msvc-InventoryManagementCRUDAPI

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/inventorydb
    url: jdbc:mysql://inventorydb.cv4qesycas0y.eu-north-1.rds.amazonaws.com:3306/inventorydb
    username: root
    #password: curso
    password: D1p4w38Cu*
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: 13.48.29.69
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka