server:
  port: 8080

spring:
  application:
    name: msvc-ApiGateway
  cloud:
    gateway:
      routes:
        - id: InventoryManagementCRUDAPI
          url: http://localhost:8090
          predicates:
            - Path=/api/crud/**
        - id: InventoryReportsAPI
          url: http://localhost:9090
          predicates:
            - Path=/api/inform/**