server:
  port: 9090

spring:
  application:
    name: msvc-InventoryReportsAPI

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/reportsdb
    username: postgres
    password: curso
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka