server:
  port: 8761

spring:
  application:
    name: msvc-eureka
eureka:
  instance:
    #hostname: 13.48.29.69
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    server-Url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}