server:
  port: 8081
  address: 13.48.29.69

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: InventoryManagementCRUDAPI
          uri: http://13.48.29.69:8090
          predicates:
            - Path=/api/crud/**
        - id: InventoryReportsAPI
          uri: http://13.48.29.69:9090
          predicates:
            - Path=/api/inform/**