server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  config:
    #import: optional:configserver:http://13.48.29.69:8888
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations