server:
  port: 8090

spring:
  application:
    name: msvc-InventoryManagementCRUDAPI
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventorydb
    username: root
    password: curso
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
        defaultZone: http://${eureka.instance.hostname}:8761/eureka